###CATEGORIAS

### get all
GET http://localhost:3000/api/categorias HTTP/1.1
//Content-Type: application/json

### get One
GET http://localhost:3000/api/categorias/6211816aafce1a3ee137debc HTTP/1.1

### create
POST http://localhost:3000/api/categorias HTTP/1.1
Content-Type: application/json

{
    "nombre": "Nueva Categoria",
    "img": "./assets/cat6.png"
}

### update
PUT http://localhost:3000/api/categorias/6228d730f9cf603923a23c4a HTTP/1.1
Content-Type: application/json

{
    "nombre": "Postres",
    "img": "../assets/postres.png"
}

### Delete
DELETE  http://localhost:3000/api/categorias/6228d730f9cf603923a23c4a HTTP/1.1


###PRODUCTOS
### create
POST http://localhost:3000/api/productos HTTP/1.1
Content-Type: application/json

{
    "nombre": "Empanadeta con idCategoria",
    "precio": 150,
    "img": "../assets/img_empanada.png",
    "descripcion": "mil millones de puntos",
    "categoria": "62118187afce1a3ee137dec0"
}

### get all
GET http://localhost:3000/api/productos HTTP/1.1
//Content-Type: application/json
    
### get One
GET http://localhost:3000/api/productos/6228d0165e4784674d07c0a8 HTTP/1.1

### update
PUT http://localhost:3000/api/productos/6228d760f9cf603923a23c4e HTTP/1.1
Content-Type: application/json

{
    "nombre": "pizza",
    "precio": 600,
    "img": "../assets/logo.png",
    "descripcion": "anana con cereza"

}

### Delete
DELETE  http://localhost:3000/api/productos/6228d760f9cf603923a23c4e HTTP/1.1


###PEDIDOS
### Create
POST http://localhost:3000/api/pedidos HTTP/1.1
Content-Type: application/json

{
    "detalle": [
        {"producto": "62105c72b67a5a720a6d4be6", "cantidad": 1},
        {"producto": "622a8e3e925cc34246db0988", "cantidad": 2},
        {"producto": "622a8dc9925cc34246db0986", "cantidad": 3}
        ],
    "precioTotal":2323,
    "nombre": "Christian",
    "direccion": "Calle abc",
    "telefono": "111133335555",
    "nota": "grabo varios productos en detalle"
}

### get all
GET http://localhost:3000/api/pedidos/ HTTP/1.1

### get One
GET http://localhost:3000/api/pedidos/ HTTP/1.1


### update
PUT http://localhost:3000/api/pedidos/ HTTP/1.1
Content-Type: application/json

{
    "detalle": "[id-prod: array objetos carrito]",
    "nombre": "Christian",
    "direccion": "Calle 123",
    "telefono": "1122223333",
    "nota": "pedido y nota modificados"
}

### delete
DELETE  http://localhost:3000/api/pedidos/6211850e0991ea0cc0983602 HTTP/1.1
